### ISSUE TITLE
Hi from APIs.guru :)

### ISSUE THREAD

**Issue by IvanGoncharov** [sendgrid/sendgrid-swagger#5]
@thinkingserious Thank you for sharing Swagger spec for your API.

I working on open [catalog](https://github.com/APIs-guru/api-models) of API specs, something like "Wikipedia for Web APIs".
Most important thing is that aggregate specs from different sources and expose them through it own [API](https://github.com/APIs-guru/api-models/blob/master/API.md). This allows 3rd-party services to provide automatic integrations, see [this list](https://github.com/APIs-guru/api-models#existing-integrations).
And more integration will come in future.

I really interested in engaging API owners in this initiative so if you have time I would love to hear feedback and ideas from you.
So if you have a couple of minutes please contact me  in Skype(ivangon4arov) or Hangouts(ivan.goncharov.ua@gmail.com).

This issue just so start a conversation, so you can close it at any moment.

**Comment by mbernier** [comment]
Hey @IvanGoncharov - 

I am the Developer Experience Product Manager at SendGrid and would really enjoy a conversation with you. I will reach out over email so we can chat.

Thanks for reaching out!

**Comment by IvanGoncharov** [comment]
@mbernier Thanks for quick reply. Just answered your email.
Looking forward to speaking with you.
